### ISSUE TITLE
eval VAR replacere("%VAR", not working properly

### ISSUE THREAD

**Issue by HanryuDR** [joemcbride/outlander-osx#106]
eval fullcombo replacere("%fullcombo", "( and an? |, an? )", "\|")
that line does not update the variable full combo

 eval temp replacere("%fullcombo", "( and an? |, an? )", "\|")
 var fullcombo %temp

that works just fine

**Comment by joemcbride** [comment]
Looks like this is a dupe of #93 - just didn't realize what the issue was.

**Comment by joemcbride** [comment]
Fixed in new script engine
