### ISSUE TITLE
How to set a variable as a multiple-word noun?

### ISSUE THREAD

**Issue by tbgg** [joemcbride/outlander-osx#117]
I like to use containers in containers to keep things a little more organized, and in Genie I can set something like 
var gpcont = duffel.bag.in.my.rucksack
 and Genie knows that that means the duffel bag in my rucksack.

When I try this same thing in Outlander, it identifies gpcont as duffel, which obviously it doesn't recognize.  Even just 'duffel bag' would probably work, since that's the only duffel bag I have, but how do I assign a variable to be a multiple-word noun?

Thanks!

**Comment by tbgg** [comment]
Actually, it looks like duffel.bag works OK. But it identifies harp.case as just harp.

**Comment by joemcbride** [comment]
You can just use `var gpcont duffel bag`

**Comment by joemcbride** [comment]
Anything after the name of the variable, `gpcont` in this case, will be assigned to the variable

**Comment by tbgg** [comment]
OK, I think my problem was that I was trying to assign my variable as %2.
So the command was .assess harp harp.case and it was setting the variable to harp.  But when I hard-coded the variable to just 'harp case' and took out the command line arguments, it worked.  Is it only possible to use a single input for a script, i.e. a %1?

**Comment by joemcbride** [comment]
For script input you'll need to use quotes.

`.swap "my bag" one two`

There is a bug with the script input and using `.`. So you can use `.swap "my.duffel"` and it should work.

**Comment by joemcbride** [comment]
Going to close this - feel free to re-open if this didn't work for you.  Thanks!
