### ISSUE TITLE
Infinite Loop message prevents logging in with new 0.11.1 version

### ISSUE THREAD

**Issue by tbgg** [joemcbride/outlander-osx#119]
I just installed the new version of Outlander and was very excited about getting to set up my sounds, but as soon as I open it, and before I can even try connecting, I get that infinite loop message you added.  (And FYI, infinite is spelled with 3 i's, not 2 i's and an a).  I get the spinning disk and can't even get to the File menu to connect to see if connecting will make it go away.

Help!!!!

**Comment by joemcbride** [comment]
Hah, yeah, thanks for catching that spelling error.

Do you have triggers or aliases that would perhaps run when the app first starts?  Can you send me your Config folder?  That would probably be the easiest for me to track down the issue.  Can send it to `mcbridej at play.net`.

**Comment by tbgg** [comment]
Let me ask you this.  Is there a way to change which profile wants to load by default?  I was running too slow, particularly during combat, so I set up a scaled-down profile that I called Combat and I like that so well, it's what I've been running all the time.  I have a bunch of stuff right now in the default profile that I probably don't need, but if I could change the default profile to my Combat profile, it would keep me from having to weed out what the likely culprit is.

**Comment by joemcbride** [comment]
There currently isn't a way to configure a different profile to use on startup.  But an easy change would be to just copy the files from the `Combat` folder to the `Default` folder.

**Comment by joemcbride** [comment]
Also, the new `#class` command should help with disabling some triggers/subs/highlights too.

**Comment by tbgg** [comment]
OK, I changed the contents of my default profile and I'm in now.  Thanks!

**Comment by joemcbride** [comment]
👍  Btw, which error message were you getting?

>Possible infinite loop detected, aborting script "xyz". Please check the commands you are sending for an infinite loop.

or

> Possible infinite loop detected. Please check the commands you are sending for an infinite loop.

This detection kicks in when 50+ messages are sent for the client to process with less than 0.1 seconds between them.

**Comment by tbgg** [comment]
The second one.

**Comment by joemcbride** [comment]
This issue was most likely the same as #120
