### ISSUE TITLE
$date and $time

### ISSUE THREAD

**Issue by HanryuDR** [joemcbride/outlander-osx#126]
Would like variables with the local computer's date and time in them (for logging purposes mostly).

**Comment by HanryuDR** [comment]
$date in YYYYMMDD format plz
$time in HH:MM (maybe with ss, but I don't really need second precision for what I'm imagining)

**Comment by joemcbride** [comment]
Released in https://github.com/joemcbride/outlander-osx/releases/tag/v0.11.13
