### ISSUE TITLE
Outlander Automapper Not Working

### ISSUE THREAD

**Issue by kellensinclair** [joemcbride/outlander-osx#134]
I'm using Outlander 0.11.4 Alpha.  I copied maps into documents/outlander/maps.  I copied an Automapper.cmd into documents/outlander/scripts.

When I do "#goto 1" I get the following:
No when pattern defined action on line 227
No when pattern defined action on line 338

**Comment by HanryuDR** [comment]
You need to make sure you're using the automapper.cmd on this website, not the one for Genie. The Genie one has commands that don't work with Outlander.

https://github.com/joemcbride/outlander-osx-scripts

**Comment by kellensinclair** [comment]
How do I save that automapper file?

I see the script text for it, but how do i download the .cmd file?

**Comment by HanryuDR** [comment]
hold control, click the file name (in the big list), select "download file"

**Comment by HanryuDR** [comment]
then move that to the scripts folder (probably under docs/outlander/scripts)

**Comment by joemcbride** [comment]
It may be easiest just copy/paste the text into the existing .cmd file.

@HanryuDR Which browser are you using?  When I do that with Safari it downloads an html file, which wouldn't work.

**Comment by HanryuDR** [comment]
Safari,yea not working. I must have dowloaded the whole thing with the button at the top, or maybe svn

**Comment by joemcbride** [comment]
Another option

1. Click on the file in the list
2. Click the "raw" button ![screen shot 2017-05-15 at 7 32 55 pm](https://cloud.githubusercontent.com/assets/255007/26087381/54f6dd32-39a5-11e7-840f-bcc426120598.png)
3. File -> Save As

If using Safari, make sure to choose "Page Source", so it only saves the text.  To convert the .txt file to a .cmd file you will probably have to enable "Show all filename extensions" on the Advanced tab of Finder Settings.

**Comment by kellensinclair** [comment]
Thanks guys!

I copied and pasted the text into the existing .cmd file

**Comment by kellensinclair** [comment]
forget to say that worked. ^^
