### ISSUE TITLE
Highlighting 

### ISSUE THREAD

**Issue by kellensinclair** [joemcbride/outlander-osx#135]
I have version 0.11.4 alpha.  How can I highlight names?

**Comment by HanryuDR** [comment]
cmd , (or go do Outlander, Prefs.) then click the + button and add the highlight. You'll need to specify a color with it's hex code. While you can't use the color picker, I still like to bring it up to see hex codes (cmd shift c) and then select "web safe colors" from the dropdown menu.

**Comment by kellensinclair** [comment]
How do I highlight a name?

If I do what you said, it does not have a place to put a name to highlight.

**Comment by kellensinclair** [comment]
Never mind.  I typed in name on Highlight line.
