### ISSUE TITLE
Feature Request: Accessing the info in percwindow

### ISSUE THREAD

**Issue by Antendren** [joemcbride/outlander-osx#136]
There's wonderfully useful information in the percwindow about spell duration and OM charge (and maybe other things?).  I'd like some way to access that information in a script.  Maybe just a general command to grab the contents of a window; I could parse it from there.  Or maybe a way to pull the specific spell information from upstream somehow; I don't know the details of how the game is sending that.

Edit: Or a command to run a regex against the contents of a given window.

**Comment by HanryuDR** [comment]
I added a bunch of triggers to capture durations at least like so:

#trigger {^Ease Burden\s+\((\d+).*\)$} {#var EASE $1}
#trigger {^Manifest Force\s+\((\d+).*\)$} {#var MAF $1}
#trigger {^Wolf Scent\s+\((\d+).*\)$} {#var WS $1}
#trigger {^See the Wind\s+\((\d+).*\)$} {#var STW $1}
#trigger {^Instinct\s+\((\d+).*\)$} {#var INST $1}
#trigger {^Senses of the Tiger\s+\((\d+).*\)$} {#var SOTT $1}
#trigger {^Wisdom of the Pack\s+\((\d+).*\)$} {#var WOTP $1}
#trigger {^Claws of the Cougar\s+\((\d+).*\)$} {#var COTC $1}
#trigger {^Hands of Lirisa\s+\((\d+).*\)$} {#var HOL $1}
#trigger {^Earth Meld\s+\((\d+).*\)$} {#var EM $1}
#trigger {^Essence of Yew\s+\((\d+).*\)$} {#var EY $1}
#trigger {^Blend\s+\((\d+).*\)$} {#var BLEND $1}
#trigger {^Skein of Shadows\s+\((\d+).*\)$} {#var SKS $1}
#trigger {^Oath of the Firstborn\s+\((\d+).*\)$} {#var OATH $1}
#trigger {^Athleticism\s+\((\d+).*\)$} {#var ATH $1}
#trigger {^Memory of Nature\s+\((\d+).*\)$} {#var MON $1}
#trigger {^Cheetah Swiftness\s+\(.*\)$} {#var CS 100}
#trigger {^Bear Strength\s+\(.*\)$} {#var BES 100}

**Comment by Antendren** [comment]
Will those match on text in the percwindow?

_False edit:_ Apparently so.  Nevermind, problem solved.  Thanks.
