### ISSUE TITLE
Nested gosubs bug

### ISSUE THREAD

**Issue by Antendren** [joemcbride/outlander-osx#137]
This is on 0.11.4

There seems to be a bug when gosubs are nested to depth 3 or higher.  Returns aren't always backing out as they should.  Consider the following code:

```
gosub level1
echo Done
exit


level1:
	pause 0.1
	gosub level2
	pause 0.1
	return

	echo level1 failure
	return

level2:
	pause 0.1
	gosub level3
	pause 0.1
	return

	echo level2 failure
	return

level3:
	pause 0.1
	gosub level4
	pause 0.1
	return

	echo level3 failure
	return

level4:
	pause 0.1
	gosub level5
	pause 0.1
	return

	echo level4 failure
	return

level5:
	pause 0.1
	return
	echo level 5 failure
	return
```

This produces the following result:

> level3 failure
> level2 failure
> level1 failure
> Done

**Comment by joemcbride** [comment]
Thanks for the report!  You may be happy to know that I've completely rewritten the script engine to fix issues such as this.  I am currently working on overhauling the text processing of highlights/triggers/substitutes.  I don't have an eta for when the text processing will be done, though you can download the beta client and try out the new script engine.

You can download the beta by changing a setting in the app.cfg file.

**Comment by Antendren** [comment]
That's great to hear.  I'll give it a go.
