### ISSUE TITLE
Maps not loading in Automapper during play.

### ISSUE THREAD

**Issue by kpick** [joemcbride/outlander-osx#140]
Hi.

So, when I load the application, it tells me that all the maps are loaded correctly. I've checked the directory to make sure there are only maps in there, checked the file permissions to make sure they're accessible, and I can see them in the menuing of the AutoMapper UI. However, none of the maps can be selected, and any commands give the error: "[AutoMapper] no map data loaded". 

Since I see the initial load, I'm assuming the maps are at least partially loaded. I downloaded the project to check out the code, but I can't actually run it since the version of OysterKit is incompatible with my version of XCode... Otherwise I'd trace it myself.

Any suggestions?

-Ken-

**Comment by joemcbride** [comment]
Can you provide a screenshot of what your Maps folder on disk looks like?

**Comment by kpick** [comment]
Sure!
<img width="1223" alt="screen shot 2017-07-29 at 12 12 43 pm" src="https://user-images.githubusercontent.com/6217397/28746300-7b242004-7457-11e7-8248-0a119f803024.png">
<img width="883" alt="screen shot 2017-07-29 at 12 13 27 pm" src="https://user-images.githubusercontent.com/6217397/28746301-7b27178c-7457-11e7-9f2f-1dfb207bd410.png">

 Attached.

**Comment by joemcbride** [comment]
Thanks - that looks fine to me - can you also provide a screenshot of what it says on startup?  Does it say how many maps are loaded?  Did you add the Outlander specific automapper script to your script folder?

**Comment by kpick** [comment]
Yeah. I'm just about to drive somewhere... I'll send detailed screens in a
few hours. On start up, it says 106 maps loaded.

I used the automapper script loaded from the instructions. I can manually
invoke it, but it doesn't do anything. (I.e. starts and stops in 100ms). I
can also invoke #goto, but it says [AutoMapper] No Maps Loaded and exits
out.

Ken

**Comment by joemcbride** [comment]
What it seems to be is that the maps are loading into memory, though it can't find the specific room your character is in.  What area is your character in?  It should attempt to find what room you're in every time you travel to a new room.  Right now it does get confused in some areas, especially areas where the room description is the same.

**Comment by kpick** [comment]
I think one of the map files might've had some weird data in it. I removed
some of the festival/quest maps and was able to get it to load in the
window. Then, I fixed the automapper script... (line 24 is &0, which errors
out. $0 works).

I'll keep you in the loop when I find out which of the maps in the GEnie
repo is doing it.

**Comment by kpick** [comment]
Also, your app is pretty awesome. I'm excited to have such a great client
for the Mac.

**Comment by joemcbride** [comment]
Okay good to know. I haven't updated my maps from source for a while.  All of the Genie Maps are saved as UTF16, so perhaps one was saved under a different encoding and it's throwing things off.  There is another issue about the festival maps causing problems, so need to update to ignore sub folders of maps.

**Comment by joemcbride** [comment]
Added the ignoring of map subfolders in [0.11.5](https://github.com/joemcbride/outlander-osx/releases/tag/v0.11.5) and tested with the latest Genie maps.  Going to close this for now.  Feel free to re-open if you have issues after this.

**Comment by joemcbride** [comment]
May have found the _real_ issue.  The _real_ issue appears to be that the `zoneid` and `roomid` variables are not getting initialized.

You can type these from the command prompt:

```
#var zoneid 1
#var roomid 1
```

`File -> Save Profile` to save the variables, then restart Outlander.
