### ISSUE TITLE
labels with spaces

### ISSUE THREAD

**Issue by HanryuDR** [joemcbride/outlander-osx#145]
allow me a way to have tables with spaces in them either with some character representation of space (._) or in quote ("carving knife": )

**Comment by joemcbride** [comment]
Don't have plans for quotes, but the good news is `.` and `_` should work in both the old engine and the new engine.  I have seen a few issues in the old engine with `.` however.

**Comment by HanryuDR** [comment]
Here's my problem, I have a script that pulls items for repair then if they don't need repairing puts them back in certain containers. I have a "carving knife" that I try to repair and after trying I want it to go to label
```carving knife:```
however this does not work.
I ran this script also with . and _ and neither works.
What am I doing wrong?

```
debug level 5
var temp jump cut
echo **%temp**
goto %temp
exit
jump_cut:
echo **jump_cut**
exit
jump.cut:
echo **jump.cut**
exit
jump cut:
echo **jump cut**
exit
```

**Comment by joemcbride** [comment]
Since spaces are not supported, you need to replace the space with something else.

```
debug level 5
var temp jump cut
eval temp replacere("%temp", " ", "_")
echo **%temp**
goto %temp
exit
jump_cut:
echo **jump_cut**
exit
jump.cut:
echo **jump.cut**
exit
jump cut:
echo **jump cut**
exit
```

**Comment by HanryuDR** [comment]
I know, therefore my request that spaces be allowed, or that the engine auto-replace spaces in a ```goto``` with either ```.``` or ```_``` :D

**Comment by joemcbride** [comment]
Honestly not something I want to implement.  It complicates too many things.

**Comment by joemcbride** [comment]
Closing as per my above comment.
