### ISSUE TITLE
Map dropdown menu never works

### ISSUE THREAD

**Issue by HanryuDR** [joemcbride/outlander-osx#149]
The dropdown menu in the map window does not drop down to let you select other maps.

**Comment by joemcbride** [comment]
This unfortunately has been broken since the release of macOS Sierra (or even the OS previous to that?).  I've looked at it several times and I'm not sure why it quit working.  This is on the list for mapping overhaul.

**Comment by HanryuDR** [comment]
AH, ok. Yes this is happening on

~~Daniel

**Comment by joemcbride** [comment]
I've noticed that you _can_ use the keyboard to switch maps.  Click on the drop-down icon, then click into the Textbox.  Then use the keyboard.  Use `#mapper reset` to go back to your current map.
