### ISSUE TITLE
Reloading profile does not respect window order

### ISSUE THREAD

**Issue by HanryuDR** [joemcbride/outlander-osx#150]
If you are logged in, and you use connect with profile to reselect the profile you are on, it does not respect window order present in the profile.

**Comment by joemcbride** [comment]
@HanryuDR This should be fixed now, yes?

**Comment by HanryuDR** [comment]
This does seem to be fixed, but I have changed the permissions on my layout files to read only (even by the system) so that might have some effect.

**Comment by joemcbride** [comment]
Closing this as fixed.
