### ISSUE TITLE
Change layouts to be shared

### ISSUE THREAD

**Issue by joemcbride** [joemcbride/outlander-osx#161]
Instead of each character profile having its own layout, move layouts to a shared folder and set a "default" one for the profile.  Create a `Layout` menu to load/save.

**Comment by HanryuDR** [comment]
This does seem to be fixed, but I have changed the permissions on my layout files to read only (even by the system) so that might have some effect.

**Comment by joemcbride** [comment]
Fixed in 0.11.22. https://github.com/joemcbride/outlander-osx/releases/tag/v0.11.22
