### ISSUE TITLE
scripting/functionality

### ISSUE THREAD

**Issue by kellensinclair** [joemcbride/outlander-osx#176]
Does Outlander support all the same scripting functionality / plugins as Genie?

**Comment by joemcbride** [comment]
It does not yet support all of genies scripting functionality, though it is close.  It supports both global and script specific variables, gosub, actions and triggers, as well as some other advanced features such as `#parse`.  It’s not without a few issues admittedly, though I personally switched to Outlander from Genie a few years ago.  Some power users have pushed its limits.

Available scripting functionality:  
https://github.com/joemcbride/outlander-osx/blob/master/commands.md

It does not yet have plugins.

Feel free to join the Discord chat to get some other opinions from current users.   
https://discord.gg/XqyCNEq
