### ISSUE TITLE
Empath’s Touch

### ISSUE THREAD

**Issue by pjcaruso** [joemcbride/outlander-osx#180]
I’m having an interesting experience with my empath. 

When he touches a patient, the list of injuries doesn’t populate the window. Is this data going somewhere else?

**Comment by joemcbride** [comment]
By default DragonRealms sends this info to the familiar window.  Do you have that window showing?

`#window list all` will show all of the configured windows.

Do `#window show familiar` to show that window.

See the player documentation for all available commands.  https://github.com/joemcbride/outlander-osx/blob/master/commands.md

**Comment by pjcaruso** [comment]
I suspected it was being sent somewhere, I just couldn’t figure out where. No, I don’t have the familiar window active, but I’ll put it into that template.

 

Thank You

**Comment by joemcbride** [comment]
Welcome!
