### ISSUE TITLE
Strong Password Authentication Not Supported

### ISSUE THREAD

**Issue by skyleronken** [joemcbride/outlander-osx#42]
With the addition of F2P, the authentication process seems to have changed so that F2P accounts cannot utilize Outlander. Avalon had to be updated to permit F2P accounts as well. Not an issue for subscribers, but definitely for F2P accounts.

**Comment by joemcbride** [comment]
I have been using Outlander (built from source) with a F2P account.  I also just tested the F2P account with the released v0.4 version.  I did not have to change anything with Outlander for it to work.  Were you having a specific issue?

**Comment by skyleronken** [comment]
Whenever I try to connect it gives me a "invalid password" error. Have you seen this before?

**Comment by joemcbride** [comment]
I have not gotten this myself, though I have heard complaints of it.  If its what I think, there is a bug in my hashing algorithm used to connect to the game.  I had another player with this issue able to authenticate, though only after trying about a dozen times.  Perhaps we could get on a screenshare/skype session some time to attempt to work out the issue?  I think its related to either password length or specific characters in the password.

**Comment by skyleronken** [comment]
Ah okay. I am not familiar with the specific hashing algorithm they
require. I will keep trying and see if I can connect. Can you point me to
where in the code you do the hashing of the password?

**Comment by joemcbride** [comment]
Its a c function taken from I think an old version of the Warlock client.

https://github.com/joemcbride/outlander-osx/blob/master/src/Outlander/AuthenticationServer.m#L175

Here's the same function converted to C#:

https://github.com/joemcbride/outlander/blob/master/src/Pathfinder.Core/Authentication/PasswordHashProvider.cs

**Comment by joemcbride** [comment]
More info here.

http://warlock.sourceforge.net/Wikka/wikka.php?wakka=EAccessProtocol

**Comment by joemcbride** [comment]
With the help of ZARPREY I have been able to confirm that this is related to specific characters in the password. For anyone else having this issue you can change your password to all lowercase letters and you can authenticate.  Not ideal for sure.

Some insights from Warlock here.  https://github.com/sproctor/warlock2/blob/master/cc.warlock.core.stormfront/src/main/cc/warlock/core/stormfront/network/SGEConnection.java#L137-L140

**Comment by joemcbride** [comment]
Fix for this issue ended up being - convert characters to numbers, do hash calculation, convert result to hex, send hex over the wire as bytes.
