### ISSUE TITLE
Keypad macros don't work all the time

### ISSUE THREAD

**Issue by robert365** [joemcbride/outlander-osx#51]
Firstly, Outlander is a great app for DR. Thank you for building it. Just finished setting up the config files and noticed that sometimes when I launch Outlander, the keypad keys don't work properly. I have macros for all the keypad keys and sometimes, Outlander will just output the numbers instead of the macros. In that situation, my other macros will work, including the other keys on the keypad like + - * / =. Restarting Outlander doesn't solve it. Rebooting my Mac does. Any idea why this happens sometimes? So far this only affects the macros on the keypad when not used with another modifier key like ctrl or option. OS X 10.10.4, Outlander 0.7.2. Thanks.

**Comment by joemcbride** [comment]
Thanks!  Macros do need some love, and the keypad keys can be interesting. Can you post your macros config file?

A couple things of note.

1. If you have the settings window open that will disable all macros.  Though if some work and some don't then that can't be it.
2. Macros will not work with multiple character profiles.  So if you're logged into multiple characters, only the macros for the first character logged in will work.  This is a known bug #48.

Also, what keyboard are you using (including what country)?

Here's a simple config file of mine + a screenshot of the settings window:

```
#macro {91} {#send north}
#macro {84} {#send south}
#macro {88} {#send east}
#macro {86} {#send west}
#macro {89} {#send northwest}
#macro {92} {#send northeast}
#macro {83} {#send southwest}
#macro {85} {#send southeast}
#macro {87} {#send out}
#macro {82} {#send down}
#macro {75} {health}
#macro {67} {exp}
#macro {78} {exp survival 0}
#macro {69} {look}
#macro {⌃91} {#send peer north}
#macro {⌃84} {#send peer south}
#macro {⌃86} {#send peer west}
#macro {⌃88} {#send peer east}
#macro {⌃83} {#send peer southwest}
#macro {⌃85} {#send peer southeast}
#macro {⌃89} {#send peer northwest}
#macro {⌃92} {#send peer northeast}
#macro {⌃87} {#send peer out}
#macro {⌃82} {#send peer down}
#macro {⌃65} {#send peer up}
#macro {⌃50} {#script abort all}
```
![screen shot 2015-07-24 at 7 55 35 pm](https://cloud.githubusercontent.com/assets/255007/8887596/f591f81a-323d-11e5-82f2-a9d61c246f73.png)

**Comment by robert365** [comment]
Thanks for the quick response. Unfortunately, I didn't have the Settings window open and I only have 1 character. I am using a Mac extended keyboard, with US English selected as language. This is what my macros.cfg file looks like:

#macro {87} {out}
#macro {89} {nw}
#macro {91} {n}
#macro {92} {ne}
#macro {86} {w}
#macro {88} {e}
#macro {83} {sw}
#macro {84} {s}
#macro {85} {se}
#macro {78} {up}
#macro {69} {down}
#macro {81} {info}
#macro {75} {health}
#macro {67} {exp all}
#macro {82} {look at $enemy}
#macro {65} {stat}

{87} - {85} sometimes don't work, but the ones below that always work fine. Also, the ones below also always work fine:

#macro {⌥89} {peer nw}
#macro {⌥91} {peer n}
#macro {⌥92} {peer ne}
#macro {⌥86} {peer w}
#macro {⌥88} {peer e}
#macro {⌥83} {peer sw}
#macro {⌥84} {peer s}
#macro {⌥85} {peer se}
#macro {⌥87} {peer out}

I noticed that you use #send for some macros but not others. Why is that? Thanks for your help.

**Comment by joemcbride** [comment]
`#send` will queue up the command and wait for roundtime if there is any.  So if you travel into a room with roundtime (like a river), you can still just hit the macro once instead of manually waiting for roundtime.

I'm out of town this week so won't be able to look into this deeper until next week, though I just had a thought.  Are you perhaps toggling `Num Lock`?

http://osxdaily.com/2014/12/01/number-keys-not-working-mac-keyboard-fix/

**Comment by robert365** [comment]
I tried to toggle the Num Lock setting on and off per that tip, and couldn't trigger the error condition. Have not experienced the bug recently either. Perhaps related to when I was using a text editor to set up the cfg files instead of doing it within Outlander. Will let you know I can figure out how to trigger this error again. Thanks for responding.

**Comment by joemcbride** [comment]
Going to close this.  Feel free to re-open if you end up being able to reproduce it.
