### ISSUE TITLE
allow sending semicolon

### ISSUE THREAD

**Issue by isaachawley** [joemcbride/outlander-osx#53]
Some dragonrealms commands use the semicolon character (;), sing and chant, for example.

I can't get the outlander client to send a semicolon, even putting it in a script. Please allow this, with escaping or whatever is necessary.

Possible docs issue - maybe there's a way but it needs to be in the README.

**Comment by joemcbride** [comment]
Right now the semicolon is used to send multiple commands at once:

```
put say hello;say DragonRealms
```

This will send `say hello` and `say DragonRealms` as put commands.

There is no way to escape the semicolon currently.

**Comment by isaachawley** [comment]
Bummer, that breaks sing and chant.
https://elanthipedia.play.net/mediawiki/index.php/Sing_command

**Comment by joemcbride** [comment]
I should be able to fix this without too much trouble.  I'm not sure how soon since I am out of town.  May see how far I can get on it on my train ride today.

**Comment by isaachawley** [comment]
Great. I'm impressed that you read these.

**Comment by joemcbride** [comment]
Fixed in [v0.7.3](https://github.com/joemcbride/outlander-osx/releases/tag/v0.7.3)
