### ISSUE TITLE
Variable name precedence in scripts

### ISSUE THREAD

**Issue by Antendren** [joemcbride/outlander-osx#57]
Some of the built in global variables are prefixes of others, for example $lefthand and $lefthandnoun, or $game and $gametime.  At the command line, variables are resolved in what I think is called a greedy fashion: basically, try for the longest variable name you can.  In a script, though, it happens in the other fashion: stop at the first variable name you see.  This means that you can't use $lefthandnoun in a script, because $lefthand takes precedence, and similarly $gametime and $game.

**Comment by joemcbride** [comment]
Can I hire you as QA?  I also need to get you this updated version.  =[

![screen shot 2016-02-11 at 11 44 03 pm](https://cloud.githubusercontent.com/assets/255007/13001310/502cf458-d119-11e5-9fed-d26eb58d5c54.png)

**Comment by Antendren** [comment]
Oh, sweet.  And I suspect replacere can be used to answer the feature request I was about to type up.

**Comment by joemcbride** [comment]
My main goal was getting the automapper working better.  Enabling the following script:

```
go:
  var dir $0
  var type default
  if matchre("%dir", "^(search|swim|climb|web|muck|rt|wait|slow|drag|script|room|ice) ") then
  {
    var type $1
    eval dir replacere("%dir", "^(search|swim|web|muck|rt|wait|slow|script|room|ice) ", "")
  }
```

**Comment by Antendren** [comment]
That will be nice.  I've been making my own adjustments to the automapper, including making a .walkto that tries to recover if the walk failed somehow.

You know that in the current version, `$1` won't work in that example, right?  When using matchre to analyze a string like "%dir", it doesn't set variables like `$1`.  That was actually the feature request I was in the middle of typing up.

**Comment by Antendren** [comment]
This was my solution:

```
action (rt_stripper) var dir $1 when ^rt (.*)$
action (rt_stripper) off

go:
	var dir $0
	if contains("%dir","rt ") then {
		action (rt_stripper) on
		put #parse %dir
		pause 0.2
		action (rt_stripper) off
	}
```

**Comment by joemcbride** [comment]
Correct, it doesn't currently work.  Genie basically sets those "match group" variables anytime a regex is evaluated, which I'm not doing.  Right now it only sets those variables on `gosub`, `matchre`, and you can use them within the `action` command themselves, though they don't persist "globally".

Nice trick!

**Comment by Antendren** [comment]
I think it's probably best if an `action` command's match variables stay local to it, so that an action that goes off at the wrong time doesn't overwrite a value you were about to use.  In Yasse, this is the source of a persistent bug in my mining script that causes me to occasionally not pick up metal.

**Comment by joemcbride** [comment]
Published that "evaluate longer variables first" in 0.9.0.

**Comment by joemcbride** [comment]
Closing this as it should be fixed.
