### ISSUE TITLE
Variables in waitforre regular expressions

### ISSUE THREAD

**Issue by Antendren** [joemcbride/outlander-osx#58]
This is a request that it be possible to use variables when creating regular expressions for `action` or `waitforre`.

It's possible to use variables when creating regular expressions for `matchre`, but not for the others.  The following works:
```
	var wo_item large metal horseshoe

	matchre continue Page (\d+): (a|some) %wo_item
	put read my blacksmithing book
	matchwait

	continue:
	echo Page $1.
```
The following does not:
```
	var wo_item large metal horseshoe

	put read my blacksmithing book
	waitforre Page (\d+): (a|some) %wo_item

	echo Page $1.
```

**Comment by joemcbride** [comment]
You should be able to use `$1` and such with actions currently, though you're right, not with `waitforre`.  I ran into this myself with adding the `replacere` function.  Fixing this, in general, is actually the thing I'm currently working on fixing.

Example action:

```
action (info) var guild $1;put #var guild $1 when Guild:\s+(Barbarian|Bard|Cleric|Commoner|Empath|Moon Mage|Necromancer|Paladin|Ranger|Thief|Trader|Warrior Mage)$
```

**Comment by Antendren** [comment]
Sorry, the use of $1 in my examples was misleading.  I'm asking about the use of %wo_item.  That's what works in `matchre` but not `action`.

**Comment by joemcbride** [comment]
Ah, gotcha.  That shouldn't be too hard to add I think.
