### ISSUE TITLE
Highlight issues

### ISSUE THREAD

**Issue by dpureco** [joemcbride/outlander-osx#61]
If I have a highlight rule for the word "mana", any instances of the string mana get highlighted. This includes "manage", "manager", etc.

**Comment by joemcbride** [comment]
You can solve this by using a `\b` around `mana`, which represents a word boundary.

```
\bmana\b
```

One thing I use to test regexes is http://rubular.com - it has a reminder of available regex sequences, which is handy.  Regex is a land of its own which I often have to lookup and test things out.

Here is a test regex I tried out on rubular:

http://rubular.com/r/d21FirpwPu

**Comment by joemcbride** [comment]
The next question most people ask is - how do I highlight a whole line?

```
^(You've gained a new rank.*)$
^(.*not yet fully disarmed.*)$
```

`^` represents the start of a line.  `$` means the end.  `.*` means any single character, zero or more times.

```
#highlight {#0000ff} {^(You've gained a new rank.*)$}
```

**Comment by joemcbride** [comment]
Closing this, let me know if you have any other problems.
