### ISSUE TITLE
Populate global regex with waitforre

### ISSUE THREAD

**Issue by dpureco** [joemcbride/outlander-osx#70]
1)
put info
waitforre Guild: *(\w+)
var guild $1
That thing does not seem to waitforre

**Comment by joemcbride** [comment]
Had a thought on this ... is it not waiting for and matching the text, or is it just not populating the `guild` variable afterwards?

In this context, `var guild $1` is not currently supported.

**Comment by joemcbride** [comment]
Confirmed this with a local test - `waitforre Guild: *(\w+)` does wait and match on the regex, though `guild` isn't populated with a correct value since that isn't currently supported.

**Comment by joemcbride** [comment]
The way I currently solve this is with actions:

```
action (info) var guild $1;put #var guild $1 when Guild: *(\w+)$
action (info) var circle $1;put #var circle $1 when Circle:\s+(\d+)$

gosub checkinfo
goto end

checkinfo:
  put info
  waitfor Encumbrance
  action (info) off
  return

end:
echo Guild: %guild
echo Circle: %circle
```

**Comment by dpureco** [comment]
It may just be an issue with the overall script. This is that same long
script I told you about the other day that had a bunch of issues. I tried
going through it line by line for a bit and saw this issue pop up. But it
could be unrelated to waitfor and may be due to something else.

**Comment by joemcbride** [comment]
Done in new script engine.
