### ISSUE TITLE
turn logging off/limit buffer length?

### ISSUE THREAD

**Issue by mulderDR** [joemcbride/outlander-osx#73]
i get noticeable latency after running the game for a couple hours, wondering if it could be due to logging or buffer length and if there's a way to control those options.

**Comment by joemcbride** [comment]
There isn't currently a way to turn off logging, though I will look at adding a toggle for that.

By buffer, do you mean the primary game window buffer?  There isn't a way to limit that either, though you can manually clear it by right-clicking and selecting `clear`.  You can also use `#window clear main` at the command prompt or in a script.

**Comment by joemcbride** [comment]
Thanks for this tip btw - logging has been slowing the game down.  I switch the logging to be asynchronous and it has sped up quite a bit.  I'll work on adding a way to toggle it off entirely.

**Comment by mulderDR** [comment]
yea, was referring to the primary game window buffer, though after more careful consideration i'm fairly certain logging is the issue (latency isn't resolved by closing the window out and reconnecting in a new window [effectively clearing the buffer] - i have to entirely reboot the program). appreciate the speedy response and all your hard work putting a decent client out there for us mac users.

**Comment by joemcbride** [comment]
This is now fixed in [v.0.9.5](https://github.com/joemcbride/outlander-osx/releases/tag/v0.9.5)

**Comment by mulderDR** [comment]
awesome, thanks again.

**Comment by joemcbride** [comment]
Going to close this, let me know if you see any issues though.
