### ISSUE TITLE
Separate repository of scripts for outlander?

### ISSUE THREAD

**Issue by davebrace** [joemcbride/outlander-osx#74]
I've been hacking around writing an Outlander script and I think it would be cool to have a common place to share it with other users. 

@joemcbride what are your thoughts on possibly creating a separate repository for outlander scripts? `outlander-osx-scripts` perhaps? I'd be happy to help contribute.

**Comment by joemcbride** [comment]
Great idea, I created https://github.com/joemcbride/outlander-osx-scripts

I'll move my Outlander scripts there sometime today.

**Comment by joemcbride** [comment]
Pushed all of my more generic scripts.  I can't vouch that all of them work 100% with Outlander, though most of them should.

**Comment by davebrace** [comment]
Awesome thanks! I'll get a PR opened with one of mine shortly.
