### ISSUE TITLE
Variable in match

### ISSUE THREAD

**Issue by DogRiley** [joemcbride/outlander-osx#75]
When cycling through a list of items, trying to use a variable in the match string fails.  Simple and incomplete example below

```
var names Frodo|Bilbo|Gandalf
eval namecount countsplit(%names, "|")
var i 0
CHECK:
if (%i < %namecount) {
     match LISTEN %names[%i] is teaching
     send assess teach
     math i add 1
     goto CHECK
}
```

**Comment by joemcbride** [comment]
Hm, this may be related to using the indexing + the variables.  Variables are getting evaluated with `match` as of version 0.9.0.

**Comment by joemcbride** [comment]
Just realized that there is a bug in this code.

You cannot use `match` by itself.  `match` needs to be paired with a `matchwait`.  A possible fix for this:

```
var names Frodo|Bilbo|Gandalf
eval namecount countsplit(%names, "|")
var i 0
CHECK:
if (%i < %namecount) {
     match LISTEN %names[%i] is teaching
     send assess teach
     matchwait 3
     math i add 1
     goto CHECK
}
```

**Comment by joemcbride** [comment]
Closing this.
