### ISSUE TITLE
Add global paused/active script variables

### ISSUE THREAD

**Issue by DogRiley** [joemcbride/outlander-osx#76]
is there a way to directly control script execution from inside of a script without needing to go out through the front end with: put #script pause mylongrtscript

Roundtimes cause issue with the reliable execution config command (and they then fail), it would be great to evoke the pause or restart directly with say direct access to the script command for: script pause mylongrtscript

Also any way to generate a listing of active/paused scripts?

**Comment by DogRiley** [comment]
update, put seems to work, I had a syntax error, the listing of active paused would be a nice addition. :)

**Comment by joemcbride** [comment]
> reliable execution config command (and they then fail)

Can you clarify what you are referring to with this?  I don't know what you mean.

> put seems to work

Yes, you should be able to use any command that starts with `#` with `send` or `put`.

> Also any way to generate a listing of active/paused scripts?

I don't have that feature currently, though I could add that as a global variable.

**Comment by joemcbride** [comment]
Released in https://github.com/joemcbride/outlander-osx/releases/tag/v0.11.14
