### ISSUE TITLE
Issue with variables used to construct variable names

### ISSUE THREAD

**Issue by DogRiley** [joemcbride/outlander-osx#78]
There seems to be something happening when trying to use variable to construct the names of other variables to query them.  See the code below, the variable assignments are constructed identically but interpreted differently.  The order is somehow important as if you switch the order of the lines 13 and 14 your results swap.

```
setVariable Chab skullcap
setVariable ChabQuant 2

setVariable percentsign %
setVariable storecode Chab

echo percentsign: %percentsign
echo Chab: %Chab
echo ChabQuant: %ChabQuant
echo storecode: %storecode

# CHANGE THE ORDER OF THESE AND SEE THE RESULTS BELOW CHANGE
setVariable differentname %percentsign%storecodeQuant
setVariable shopdiff %percentsign%storecodeQuant


echo shopdiff: %shopdiff
echo differentname: %differentname
```

The results are:
```
percentsign: %
Chab: skullcap
ChabQuant: 2
storecode: Chab
shopdiff: 2
differentname: skullcapQuant
```

Any thoughts you have would be appriciated

**Comment by joemcbride** [comment]
Does seem like a possible bug, can look into it.

**Comment by joemcbride** [comment]
Confirmed that this is a bug, will work on a fix.

**Comment by joemcbride** [comment]
Released [0.9.6](https://github.com/joemcbride/outlander-osx/releases/tag/v0.9.6) which should fix that bug.  Let me know if you see otherwise.

One thing that I noticed is your use of `percentsign` as a variable.  I'm not sure that you need to use that.

```
setVariable shopdiff %%storecodeQuant
```

That should work as well, if you want to simplify it a bit.

**Comment by DogRiley** [comment]
Thanks, I figured out the %% via testing.  The percentsign is carried over from the progressive steal script, It seems to work as is and I am just adapting, not rewriting the thing :)  

I will download the new client and test this and let you know how it is working IRL.

**Comment by joemcbride** [comment]
Going to mark this as closed.  Let me know if you see it not working.
