### ISSUE TITLE
Remove SwiftRegex use of ~=

### ISSUE THREAD

**Issue by joemcbride** [joemcbride/outlander-osx#79]
This explains a few behavior oddities.

**Comment by DogRiley** [comment]
are all swift regex functions available ?

**Comment by joemcbride** [comment]
This is related to the native swift/objective-c code.  You should be able to use all of the basic regex commands in the scripting language.  I haven't tested out advanced things such as negative look aheads and stuff like that.

**Comment by joemcbride** [comment]
This is fixed in new script engine.
