### ISSUE TITLE
Enhancement-setmap from command line

### ISSUE THREAD

**Issue by DogRiley** [joemcbride/outlander-osx#80]
sometimes the map gets confused, esp if 2 clients are running at the same time.

to fix the issue you just go to the mapper, select any other map and then re-select the appropriate map and your automapper issue i resolved.

can you expose a command to setmap # or something ?

PS Having a great time with it, thanks alot.

**Comment by joemcbride** [comment]
Genie has a `#mapper reset` command.  I think that will work great for this.

**Comment by joemcbride** [comment]
`#mapper reset` was added in [v0.9.7](https://github.com/joemcbride/outlander-osx/releases/tag/v0.9.7)
