### ISSUE TITLE
Genie maps archive out of date

### ISSUE THREAD

**Issue by davebrace** [joemcbride/outlander-osx#81]
The link to the Genie maps is to an archive that is a few years old - I've noticed that sometimes the maps don't work correctly in game. The actual Sourceforge SVN repository is under active development with lots of updates to the maps in the last three years: https://sourceforge.net/p/geniemapsfordr/Genie3Maps/HEAD/tree/trunk/

To solve this myself, I created a mirror of the Sourceforge repo on Github and I just cloned that into my Maps folder: https://github.com/davebrace/genie_maps_for_dr

**Comment by joemcbride** [comment]
Just to clarify, this is due to the crappy sourceforge UI, and that they added an additional download a few years ago.  The links ARE correct.  I'll add this image to the docs:

![image](https://cloud.githubusercontent.com/assets/255007/18225669/bfe60d00-71ac-11e6-9c15-16712142465a.png)

**Comment by davebrace** [comment]
Ah - I missed that. I must have clicked the wrong old link when I first downloaded them a while back.

Thanks for clarifying!
