### ISSUE TITLE
echo changes the word "random " to lower case

### ISSUE THREAD

**Issue by Antendren** [joemcbride/outlander-osx#85]
This is an odd one.  It only happens with echo inside a script, and it only happens with the word "random ".  Note the space at the end.  So:

```
echo Random things.
# prints random things.
echo SUCH RANDOM STUFF.
# prints SUCH random STUFF.
echo Very rAnDoM behaviour.
# prints Very random behaviour.
```

**Comment by joemcbride** [comment]
I believe this is because `random` is a keyword and so it gets transformed to lowercase.

**Comment by joemcbride** [comment]
Have this fixed in the new script engine.
