### ISSUE TITLE
Not enough precision for keeping timers

### ISSUE THREAD

**Issue by Antendren** [joemcbride/outlander-osx#86]
I want to use the hunt verb to train perception in combat, but it only teaches every ~75 seconds, so I want to avoid hunting more often than that.  It seems like the way to accomplish this would be:
```
var no_hunt_until $gametime
math no_hunt_until add 80
...
if %no_hunt_until < $gametime ...
```

But running a variable through the math command doesn't retain enough precision.  Here's a code snippet:
```
var no_hunt_until $gametime
math no_hunt_until add 80

echo Gametime:$gametime
echo No_hunt_until:%no_hunt_until
exit
```
And here's some sample output:
```
Gametime:1477908107
No_hunt_until:1.47791e+09
```

**Comment by joemcbride** [comment]
Thanks for the report!

**Comment by joemcbride** [comment]
Have this fixed in the new script engine.
