### ISSUE TITLE
Highlights

### ISSUE THREAD

**Issue by pjcaruso** [joemcbride/outlander-osx#87]
The dark blue highlight on black is problematic. If the preferences settings could be enhanced to allow for easier, and multiple color selections for highlights, this would increase usability.

I see that there is already a ticket open for attaching sounds to a highlight. #

**Comment by joemcbride** [comment]
Can you expand on what you mean by "multiple color selections"?  Do you mean editing multiple highlights at once?

**Comment by pjcaruso** [comment]
I apologize for being obtuse.

 

I can create a highlight, but I cannot change the color of that highlight. The only option that I can discern is to use the selected dark blue. Dark blue on black is problematic, and there is value in having highlights of different colors.

**Comment by joemcbride** [comment]
I think there is a bug when a highlight is first created in the UI that it doesn't select the created one correctly.  Scroll to the bottom of the list and select the "blank" looking highlight.  Then you can add the color and it will save.

**Comment by pjcaruso** [comment]
I have apparently completely buggered Highlights.

I only had the one created, and that was for the word "You"--there was no blank one underneath it. I deleted that, and now when I go to add one, I get the alpha numeric sequence, which I believe identifies color, but am unable to enter a highlight strong. 
![screenshot 2016-11-02 20 27 34](https://cloud.githubusercontent.com/assets/23225003/19952407/64cc0aa0-a13b-11e6-9661-2a3c826e6389.png)

**Comment by joemcbride** [comment]
That looks like it is working just fine.  Click on one of the items in the list then manually type in the highlight color and text.

Here is a website that can help with hex color codes: http://htmlcolorcodes.com/

Ex:

![image](https://cloud.githubusercontent.com/assets/255007/20224416/41a428b4-a7f3-11e6-8498-01c1c4318cca.png)

**Comment by pjcaruso** [comment]
Ahh, brilliant.

 

Is it possible to change the size of the type in a window, or any of the default choices for text color (in particular the color choice for room name)?

 

Cheers,

 

Paul

**Comment by joemcbride** [comment]
You can change the font and font size of each window in the `layout.cfg` file.  You'll want to change `fontSize`, `fontName`, `monoFontSize` and `monoFontName`.

You unfortunately cannot change the color of those "presets" currently, room name, thoughts, creatures, etc.

![image](https://cloud.githubusercontent.com/assets/255007/20225654/6ac7047c-a7f9-11e6-8f51-8a658e137c04.png)

**Comment by pjcaruso** [comment]
Interesting. I will try to be careful about what I do in there. Is there a particular application that is best to employ when trying to open a .cfg file?

**Comment by joemcbride** [comment]
Any text editor should work.  I typically use [Atom](https://atom.io/) or [Sublime text 3](https://www.sublimetext.com/3).

**Comment by joemcbride** [comment]
Eventually all of these settings will be in a nice UI, just not there yet!

**Comment by pjcaruso** [comment]
Nice

 

I used Atom and the changes were easy. Interesting assortment of windows. Do they all work, and if so how do you add one in that isn’t part of the stock arrangement?

 

Atom was also the solution to the script problem. I opened up one of the script files, copied it into a new Atom file, saved it and poof—it works. How cool is that?

 

Best,

 

Paul

**Comment by joemcbride** [comment]
You can use the `#window` command.  I typically have a `log` window myself.

* `#window add/show/hide/clear <name>`
  * ex: `#window add log`
  * ex: `#window hide log`
  * `#window list all` will show all window ids and locations.
    * The output: (x,y), (height, width)
    * x,y being the point of the top-left corner.  Height going down, width accross.
  ```
  Windows:
    thoughts: (0,0), (150, 438)
    log: (0,149), (111, 438)
    main: (0,258), (432, 1021)
    logons: (1020,0), (131, 380)
    death: (1020,129), (100, 380)
    experience: (1020,228), (462, 380)
    room: (437,0), (260, 584)
    percwindow: (748,150), (148, 273)
    (hidden) atmospherics: (0,0), (200, 200)
    (hidden) chatter: (0,0), (200, 200)
    (hidden) conversation: (0,0), (200, 200)
    (hidden) familiar: (0,0), (200, 200)
    (hidden) group: (0,0), (200, 200)
    (hidden) inv: (0,0), (200, 200)
    (hidden) ooc: (0,0), (200, 200)
    (hidden) whispers: (0,0), (200, 200)
    (hidden) raw: (554,286), (275, 791)
    (hidden) assess: (782,502), (177, 567)
    (hidden) talk: (801,306), (200, 200)
  ```
  * `#window clear log` will clear all contents of the window

I then add a trigger to post a notification to the `log` window when a rank is gained.

### triggers.cfg
```
#trigger {^You've gained (?:a new|\d+) (?:rank|ranks) in\s?(?:your ability (?:to|with)|using|maneuvering in|maneuvering with a|your)?\s?(.+)\s?(?:use|area)?\.$} {#echo >log #ffff00 New Rank: $1}
```

Now lets say there is a window that you don't want open, like `talk` or `conversation`, but you would like to see that info.  For instance, it would be nice to see all of the conversation go to another window so its easier to not lose track of it in high scroll.  You can redirect that output to another window, such as `log`.  This is what I do.  I redirect `ooc`, `talk`, and `conversation` to the `log` window.  You can do that by setting the `closedTarget` value in the `layout.cfg` file.

```
talk -> conversation
conversation -> log
ooc -> log
```

```
    {
      "bufferSize" : 1000,
      "x" : 801,
      "timestamp" : 0,
      "monoFontName" : "Menlo",
      "y" : 306,
      "width" : 200,
      "monoFontSize" : 13,
      "closedTarget" : "conversation",
      "title" : "Talk",
      "showBorder" : 1,
      "bufferClearSize" : 50,
      "visible" : 0,
      "height" : 200,
      "fontSize" : 14,
      "fontName" : "Helvetica",
      "name" : "talk"
    },
    {
      "bufferSize" : 1000,
      "x" : 0,
      "timestamp" : 0,
      "monoFontName" : "Menlo",
      "y" : 0,
      "width" : 200,
      "monoFontSize" : 13,
      "closedTarget" : "log",
      "title" : "Conversation",
      "showBorder" : 1,
      "bufferClearSize" : 50,
      "visible" : 0,
      "height" : 200,
      "fontSize" : 14,
      "fontName" : "Helvetica",
      "name" : "conversation"
    },
    {
      "bufferSize" : 1000,
      "x" : 0,
      "timestamp" : 0,
      "monoFontName" : "Menlo",
      "y" : 0,
      "width" : 200,
      "monoFontSize" : 13,
      "closedTarget" : "log",
      "title" : "OOC",
      "showBorder" : 1,
      "bufferClearSize" : 50,
      "visible" : 0,
      "height" : 200,
      "fontSize" : 14,
      "fontName" : "Helvetica",
      "name" : "ooc"
    },
```

**Comment by pjcaruso** [comment]
And yes, I’m saving all these data points for the wiki J

**Comment by pjcaruso** [comment]
One last question and I promise to leave you be for a while (btw, I hope you don’t feel any pressure to respond quickly—I can be quite patient)

 

In the hunt script

 

#  Critter variables 
 #
 var skinnablecritters rat|hog|goblin|boar|eel|bobcat|cougar|reaver|wolf|snowbeast|gargoyle|togball|ape|tusky|wyvern

 

Is there a limit to the number of skinnable critters that can be listed?

**Comment by joemcbride** [comment]
> Is there a limit to the number of skinnable critters that can be listed?

No limit.  You can add another critter to the list without issue.

**Comment by joemcbride** [comment]
Going to go ahead and close this issue.
