### ISSUE TITLE
Script Access

### ISSUE THREAD

**Issue by pjcaruso** [joemcbride/outlander-osx#88]
I have downloaded several of the stock scripts and placed them within the script folder --however attempting to access them using a command IG (e.g., ".braid") has no effect. 

I have repeated the process, and closed & re-opened the application to no effect.

**Comment by joemcbride** [comment]
You put the scripts in the `Documents/Outlander/Scripts` folder?

![image](https://cloud.githubusercontent.com/assets/255007/19951907/744e43e8-a11e-11e6-8302-7a7ef702389e.png)

**Comment by pjcaruso** [comment]
I did.

**Comment by joemcbride** [comment]
Did you type `".braid"` or `.braid` without the quotes?

**Comment by pjcaruso** [comment]
without the quotes

**Comment by pjcaruso** [comment]
![screenshot 2016-11-02 20 41 51](https://cloud.githubusercontent.com/assets/23225003/19952591/d6aa2f70-a13c-11e6-915f-024a11fa656a.png)
The script files appear to be in there and in the correct place--but there is no impact when I use the command

**Comment by joemcbride** [comment]
My apologies, I swore I replied to this.  Can you double-check that those are actual .cmd files?  Looking at that screenshot they look like possibly saved web pages to me.  Do you have `Show all filename extensions` turned on?  Are those perhaps actually `scrape.cmd.html` files or similar?

Finder -> Preferences -> Advanced -> Show all filename extensions

![image](https://cloud.githubusercontent.com/assets/255007/20224331/d08db960-a7f2-11e6-9133-fce4f3f31955.png)

**Comment by joemcbride** [comment]
Going to close this.   Let me know if that didn't work!
