### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by pjcaruso** [joemcbride/outlander-osx#90]
I don't think I am using Profiles correctly. I have saved changes to the default profile, but my attempts to create a profile unique to a PC have been frustrated. Are there instructions available on this point?

**Comment by joemcbride** [comment]
Creating a custom profile should be as easy as just creating a folder in the `Profiles` directory.  Once the folder is there, the application should create all of the files needed when that profile is selected using `File -> Connect To Profile` or `CMD-SHIF-L`.

![image](https://cloud.githubusercontent.com/assets/255007/19951789/9f780f8c-a11d-11e6-9d99-40177a16f02a.png)

**Comment by pjcaruso** [comment]
Interesting

 

The download didn’t create a profiles directory—is it ok to add one?

**Comment by joemcbride** [comment]
Indeed it is.  Does your user perhaps have limited permissions?  The application should create all of the needed folders.  They should look like (with only `Default` in the Profiles folder to start):

![image](https://cloud.githubusercontent.com/assets/255007/19952075/a8219d54-a11f-11e6-9505-75e42ea3bdc4.png)

**Comment by pjcaruso** [comment]
Ok, got that fixed. Profiles set up in a Profile folder. Excellent--and thank you.
