### ISSUE TITLE
Some variable names to be avoided?

### ISSUE THREAD

**Issue by Antendren** [joemcbride/outlander-osx#91]
I think there are some variable names that don't work as well.  For example, consider the following script:
```
	var stow_objects bronze bola, a polished steel poignard and a small rock.

	eval stow_objects replacere("%stow_objects", ", a |, an | and a | and an ", "|")
	eval stow_objects replacere("%stow_objects", "\|[^\|]* (?=\w*($|\|))", "|")
	eval stow_objects replacere("%stow_objects", "^[^\|]* (?=\w*($|\|))", "")

	echo Stow Objects:%stow_objects

	var feet_objects bronze bola, a polished steel poignard and a small rock.

	eval feet_objects replacere("%feet_objects", ", a |, an | and a | and an ", "|")
	eval feet_objects replacere("%feet_objects", "\|[^\|]* (?=\w*($|\|))", "|")
	eval feet_objects replacere("%feet_objects", "^[^\|]* (?=\w*($|\|))", "")

	echo Feet Objects:%feet_objects
```
It's doing the exact same thing to the two variables, so they should contain the same string at the end.  Instead, this is the output:
```
Stow Objects:bola|poignard|rock.
Feet Objects:bronze bola, a polished steel poignard and a small rock.
```
The replacere just didn't do anything to feet_objects.

I'm happy to work around it by choosing appropriate variable names, but could you give some idea what makes a variable name bad?

**Comment by joemcbride** [comment]
This is the same issue as #93 and #106 - it looks like `eval` + `replacere` doesn't like using the same variable name as both input and replacement.
