### ISSUE TITLE
Automapper Not Showing Maps

### ISSUE THREAD

**Issue by JPof81** [joemcbride/outlander-osx#94]
I've tried multiple times to download the maps, unzip the downloaded file, and place it in the outlander maps folder, and the maps will not show up in the automapper inside Outlander FE.  

I've tried putting the unzipped maps in the folder, i've tried putting the folder with the unzipped maps in the maps folder, and even tried putting the zip file in the folder.  

I also put the automapper.cmd file in the scripts folder.

What am I doing wrong?

**Comment by joemcbride** [comment]
Was Outlander running when you moved the maps into the folder?  Outlander loads the maps when the app first starts up, maybe that is the issue?

**Comment by JPof81** [comment]
I just tried restarting it, still no map files loaded

**Comment by joemcbride** [comment]
Does your folder structure look like this?

![screen shot 2016-11-28 at 12 00 37 pm](https://cloud.githubusercontent.com/assets/255007/20683812/4843b456-b562-11e6-9845-7f5462a4c1e3.png)

**Comment by JPof81** [comment]
Mine does not have that top file called .DS_Store

**Comment by joemcbride** [comment]
That's fine, `.DS_Store` is a MacOS system file that is typically hidden (I have show system files turned on).  You should just have to worry about the `Outlander` folder structure.

**Comment by JPof81** [comment]
![screen shot 2016-11-28 at 3 06 09 pm](https://cloud.githubusercontent.com/assets/24233202/20684015/3e969274-b57c-11e6-81c2-c0df2c270374.png)

That is what mine looks like

**Comment by joemcbride** [comment]
That doesn't show me what folder those files are in.  Can you do `View->Show Path Bar` in Finder?

**Comment by JPof81** [comment]
![screen shot 2016-11-28 at 3 09 31 pm](https://cloud.githubusercontent.com/assets/24233202/20684143/bb409536-b57c-11e6-8293-710cf088100d.png)

My fault, here you go:

**Comment by joemcbride** [comment]
👍 That looks right to me.  It can take several seconds for the maps to load from disk.  They take about 6 seconds on my machine, which is a new Macbook Pro.

When you start Outlander can you wait 10-15 seconds and do `CMD-M` and see if any maps display in the dropdown?

**Comment by JPof81** [comment]
![screen shot 2016-11-28 at 3 19 09 pm](https://cloud.githubusercontent.com/assets/24233202/20684481/18adb9b4-b57e-11e6-8667-aa4d5a4c3101.png)


Still blank, unfortunately!

**Comment by joemcbride** [comment]
So if you click on that dropdown that says "Maps" it is empty?  Should look something like this:

![screen shot 2016-11-28 at 1 19 00 pm](https://cloud.githubusercontent.com/assets/255007/20686370/3d394f20-b56d-11e6-8ca3-d5719f5dfa19.png)

**Comment by JPof81** [comment]
no, if i try to click the drop down menu nothing happens because no maps are loaded.

In the FE, if I type #goto it comes back with [automapper] no map data loaded

**Comment by joemcbride** [comment]
Not sure what the issue is.  Can you open the .xml map files and ensure that they are actual .xml files?

![screen shot 2016-11-28 at 1 27 46 pm](https://cloud.githubusercontent.com/assets/255007/20686664/6ea8de6c-b56e-11e6-9e55-321563b4c2ff.png)

**Comment by JPof81** [comment]
This is what I'm getting, it looks different:
![screen shot 2016-11-28 at 4 38 15 pm](https://cloud.githubusercontent.com/assets/24233202/20687107/2a5cc71c-b589-11e6-906f-4b7c576b6e90.png)

**Comment by joemcbride** [comment]
That looks okay to me.  I'm out of ideas.  I can probably write some code to help diagnose the issue.  I won't be able to do that till late tonight though.  If all else fails, I can hop on a screen share with you and see if we can get it working.

Two other questions for you:

* What OS version are you using?
* Is your user an Admin?

Sorry for the trouble!

**Comment by JPof81** [comment]
No problem, hopefully we can figure it out. It's running Sierra and my user
is an admin

**Comment by joemcbride** [comment]
Sorry, looks like I'm not able to get to this right away like I had hoped.  I will post here again once I can get those changes made.

**Comment by joemcbride** [comment]
Just an update on this.  I have made the changes to display where it is loading files from.  However when I attempted to create a deployed version I am getting some issues.  This is the first version I'm trying to deploy after updating to Xcode 8.x and Swift 2.3.  I'm not sure what the problem is yet as the application runs fine in Developer mode.  =/

**Comment by joemcbride** [comment]
I added version 0.10.  It has some optimizations turned off.  Let me know if that helps you figure out this issue.

https://github.com/joemcbride/outlander-osx/releases/tag/v0.10.0

**Comment by JPof81** [comment]
Hey Joe,

Thanks for the new version of the FE, my maps are working perfectly now.  What a difference it makes, thanks for your hard work!

**Comment by joemcbride** [comment]
Glad to hear!  Let me know if you have any other issues.
